services:
  airflow:
    build: .
    container_name: airflow
    restart: always

    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__FERNET_KEY: "jRrAA1efytzQyG9DwXyBOXxc9VQ2pKRdRutylhm13S8="
      AIRFLOW__WEBSERVER__SECRET_KEY: "random_secret_key"
      GOOGLE_CLOUD_PROJECT: data-pipeline-portfolio
      GCP_PROJECT_ID: data-pipeline-portfolio
      PYTHONPATH: /opt/airflow
      GCS_BUCKET: ecom-data-rayane

      # GCP
      GOOGLE_APPLICATION_CREDENTIALS: /opt/airflow/.config/gcloud/application_default_credentials.json

    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./src:/opt/airflow/src
      - ~/.config/gcloud:/opt/airflow/.config/gcloud
      - ./keys:/opt/airflow/keys
      - ./ecommerce_analytics/.dbt:/home/airflow/.dbt
      - ./ecommerce_analytics:/opt/airflow/dbt 
      

    ports:
      - "8080:8080"

    command: standalone