models:
  - name: int_orders
    columns:
      - name: order_id
        data_tests:
          - unique
          - not_null
      - name: customer_id
        data_tests:
          - not_null:
              config:
                severity: warn
      - name: order_date
        data_tests:
          - not_null:
              config:
                severity: warn
      - name: normalized_status
        data_tests:
          - not_null
          - accepted_values:
             values: ['DELIVERED', 'PENDING', 'CANCELLED', 'SHIPPED', 'UNKNOWN']
      - name: total_amount
        data_tests:
          - not_null
      - name: order_item_count
        data_tests:
          - not_null
      - name: number_of_product
        data_tests:
          - not_null